version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network
    command: redis-server --appendonly yes  # Habilita persistencia AOF

  kitchen-service:
    build: ./service/api-kitchen
    container_name: api-kitchen
    ports:
      - "3001:3001"
    env_file:
      - ./service/api-kitchen/.env
    depends_on:
      - db
      - redis
    networks:
      - app_network 

  warehouse-service:
    build: ./service/api-warehouse
    container_name: api-warehouse
    ports:
      - "3002:3002"
    env_file:
      - ./service/api-warehouse/.env
    depends_on:
      - db
      - redis
    networks:
      - app_network 

volumes:
  postgres_data:
  redis_data:

networks:
  app_network:
    driver: bridge

